/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package s.z_talent_manager.vista;

/**
 *
 * @author DAW1
 */
public class FrmAdminCrearUsuario extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAdminCrearUsuario.class.getName());

    /**
     * Creates new form FrmCrearUsuarioPrueba
     */
    public FrmAdminCrearUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        bntVolver = new javax.swing.JButton();
        pnlCentral = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblNomUsu = new javax.swing.JLabel();
        txtNomUsu = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblRepCorreo = new javax.swing.JLabel();
        txtRepCorreo = new javax.swing.JTextField();
        lblCreaContr = new javax.swing.JLabel();
        txtCreaContr = new javax.swing.JTextField();
        lblRepContr = new javax.swing.JLabel();
        txtRepContr = new javax.swing.JTextField();
        lblCrearCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(211, 254, 234));
        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(184, 240, 212)));
        pnlHeader.setPreferredSize(new java.awt.Dimension(769, 110));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        lblLogo.setPreferredSize(new java.awt.Dimension(400, 100));

        bntVolver.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bntVolver.setForeground(new java.awt.Color(51, 153, 102));
        bntVolver.setText("VOLVER");
        bntVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 102)));
        bntVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(bntVolver)
                .addGap(103, 103, 103))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(bntVolver)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );

        pnlPrincipal.add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlCentral.setBackground(new java.awt.Color(211, 254, 234));
        pnlCentral.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(184, 240, 212), 1, true));
        pnlCentral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(7, 48, 26));
        lblNombre.setText("Nombre :");
        lblNombre.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblNombre.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        pnlCentral.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        txtNombre.setBackground(new java.awt.Color(248, 253, 249));
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 240, 212)));
        txtNombre.setMargin(new java.awt.Insets(5, 10, 5, 10));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        pnlCentral.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 150, 30));

        lblApellidos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(7, 48, 26));
        lblApellidos.setText("Apellidos :");
        lblApellidos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblApellidos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        pnlCentral.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        txtApellidos.setBackground(new java.awt.Color(248, 253, 249));
        txtApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 240, 212)));
        txtApellidos.setMargin(new java.awt.Insets(5, 10, 5, 10));
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        pnlCentral.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 150, 30));

        lblNomUsu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblNomUsu.setForeground(new java.awt.Color(7, 48, 26));
        lblNomUsu.setText("Nombre Usuario :");
        lblNomUsu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblNomUsu.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        pnlCentral.add(lblNomUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txtNomUsu.setBackground(new java.awt.Color(248, 253, 249));
        txtNomUsu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 240, 212)));
        txtNomUsu.setMargin(new java.awt.Insets(5, 10, 5, 10));
        txtNomUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomUsuActionPerformed(evt);
            }
        });
        pnlCentral.add(txtNomUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 150, 30));

        lblCorreo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(7, 48, 26));
        lblCorreo.setText("Correo electrónico :");
        lblCorreo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblCorreo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        pnlCentral.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(248, 253, 249));
        txtCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 240, 212)));
        txtCorreo.setMargin(new java.awt.Insets(5, 10, 5, 10));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        pnlCentral.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 210, 30));

        lblRepCorreo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblRepCorreo.setForeground(new java.awt.Color(7, 48, 26));
        lblRepCorreo.setText("Repite Correo electrónico :");
        lblRepCorreo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblRepCorreo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        pnlCentral.add(lblRepCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        txtRepCorreo.setBackground(new java.awt.Color(248, 253, 249));
        txtRepCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 240, 212)));
        txtRepCorreo.setMargin(new java.awt.Insets(5, 10, 5, 10));
        txtRepCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRepCorreoActionPerformed(evt);
            }
        });
        pnlCentral.add(txtRepCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 220, 30));

        lblCreaContr.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblCreaContr.setForeground(new java.awt.Color(7, 48, 26));
        lblCreaContr.setText("Crear Contraseña : ");
        lblCreaContr.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblCreaContr.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        pnlCentral.add(lblCreaContr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        txtCreaContr.setBackground(new java.awt.Color(248, 253, 249));
        txtCreaContr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 240, 212)));
        txtCreaContr.setMargin(new java.awt.Insets(5, 10, 5, 10));
        txtCreaContr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreaContrActionPerformed(evt);
            }
        });
        pnlCentral.add(txtCreaContr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 210, 30));

        lblRepContr.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblRepContr.setForeground(new java.awt.Color(7, 48, 26));
        lblRepContr.setText("Repite Contraseña :");
        lblRepContr.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblRepContr.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        pnlCentral.add(lblRepContr, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        txtRepContr.setBackground(new java.awt.Color(248, 253, 249));
        txtRepContr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 240, 212)));
        txtRepContr.setMargin(new java.awt.Insets(5, 10, 5, 10));
        txtRepContr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRepContrActionPerformed(evt);
            }
        });
        pnlCentral.add(txtRepContr, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 220, 30));

        lblCrearCuenta.setBackground(new java.awt.Color(51, 153, 102));
        lblCrearCuenta.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        lblCrearCuenta.setText("Crear Cuenta");
        lblCrearCuenta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lblCrearCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCentral.add(lblCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        pnlPrincipal.add(pnlCentral, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1062, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVolverActionPerformed
        FrmPanelAdmin frm = new FrmPanelAdmin();
        frm.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bntVolverActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtNomUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomUsuActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtRepCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRepCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRepCorreoActionPerformed

    private void txtCreaContrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreaContrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreaContrActionPerformed

    private void txtRepContrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRepContrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRepContrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAdminCrearUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntVolver;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCreaContr;
    private javax.swing.JButton lblCrearCuenta;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNomUsu;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRepContr;
    private javax.swing.JLabel lblRepCorreo;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCreaContr;
    private javax.swing.JTextField txtNomUsu;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRepContr;
    private javax.swing.JTextField txtRepCorreo;
    // End of variables declaration//GEN-END:variables
}
