/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package s.z_talent_manager.vista;

import java.awt.Cursor;
import java.awt.Desktop;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URI;

/**
 *
 * @author maymansito
 */
public class FrmContraseñaOlvidada extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmContraseñaOlvidada.class.getName());

    /**
     * Creates new form FrmLogin
     */
    public FrmContraseñaOlvidada() {
        initComponents();
        setLocationRelativeTo(null);

        // sirve para al hacer click en el hipervinculo te redirija a la pagina   
        lblEnlaceManualUsuario.setCursor(new Cursor(Cursor.HAND_CURSOR));

        lblEnlaceManualUsuario.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    java.net.URL url = getClass().getResource("/manual/manualUsuario.html");
                    Desktop.getDesktop().browse(url.toURI());
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });

        /*Al hacer click te lleva a otro panel
        lblOlvidoContraseña.setCursor(new Cursor(Cursor.HAND_CURSOR));

        lblOlvidoContraseña.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        
        FrmOlvidoContraseña frmOlvidoContraseña= new FrmOlvidoContraseña();
        frmOlvidoContraseña.setVisible(true);
        
        
        
         
        

    }
});
         */
        lblOlvidoContraseña.setCursor(new Cursor(Cursor.HAND_CURSOR));

        lblOlvidoContraseña.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {

                try {
                    Desktop.getDesktop().browse(new URI("https://forms.gle/WU8BtuFxXNNqvkcm7"));
                } catch (Exception ex) {
                    ex.printStackTrace();
                }

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlHeader = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        lblContraseñaActual = new javax.swing.JLabel();
        txtPasswordActual = new javax.swing.JPasswordField();
        lblContraseñaNueva = new javax.swing.JLabel();
        txtPasswordNueva = new javax.swing.JPasswordField();
        lblContraseñaConfirmar = new javax.swing.JLabel();
        txtPasswordConfirmar = new javax.swing.JPasswordField();
        lblOlvidoContraseña = new javax.swing.JLabel();
        btnCambiar = new javax.swing.JButton();
        lblEnlaceManualUsuario = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        PnlBottom = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Z_Talent Manager");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        pnlHeader.setBackground(java.awt.Color.white);
        pnlHeader.setPreferredSize(new java.awt.Dimension(800, 200));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        lblLogo.setToolTipText("");
        pnlHeader.add(lblLogo);

        getContentPane().add(pnlHeader);

        pnlBody.setBackground(java.awt.Color.white);
        pnlBody.setPreferredSize(new java.awt.Dimension(800, 350));
        pnlBody.setLayout(new java.awt.GridBagLayout());

        pnlLogin.setBackground(new java.awt.Color(255, 255, 255));
        pnlLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlLogin.setMaximumSize(new java.awt.Dimension(200, 100));
        pnlLogin.setPreferredSize(new java.awt.Dimension(500, 300));
        pnlLogin.setLayout(new java.awt.GridBagLayout());

        lblContraseñaActual.setForeground(new java.awt.Color(51, 51, 51));
        lblContraseñaActual.setText("CONTRASEÑA ACTUAL:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlLogin.add(lblContraseñaActual, gridBagConstraints);

        txtPasswordActual.setBackground(new java.awt.Color(51, 153, 102));
        txtPasswordActual.setForeground(new java.awt.Color(51, 51, 51));
        txtPasswordActual.setText("jPasswordField1");
        txtPasswordActual.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPasswordActual.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlLogin.add(txtPasswordActual, gridBagConstraints);

        lblContraseñaNueva.setForeground(new java.awt.Color(51, 51, 51));
        lblContraseñaNueva.setText("NUEVA CONTRASEÑA:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlLogin.add(lblContraseñaNueva, gridBagConstraints);

        txtPasswordNueva.setBackground(new java.awt.Color(51, 153, 102));
        txtPasswordNueva.setForeground(new java.awt.Color(51, 51, 51));
        txtPasswordNueva.setText("jPasswordField1");
        txtPasswordNueva.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPasswordNueva.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlLogin.add(txtPasswordNueva, gridBagConstraints);

        lblContraseñaConfirmar.setForeground(new java.awt.Color(51, 51, 51));
        lblContraseñaConfirmar.setText("CONFIRMAR NUEVA CONTRASEÑA:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlLogin.add(lblContraseñaConfirmar, gridBagConstraints);

        txtPasswordConfirmar.setBackground(new java.awt.Color(51, 153, 102));
        txtPasswordConfirmar.setForeground(new java.awt.Color(51, 51, 51));
        txtPasswordConfirmar.setText("jPasswordField1");
        txtPasswordConfirmar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPasswordConfirmar.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlLogin.add(txtPasswordConfirmar, gridBagConstraints);

        lblOlvidoContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOlvidoContraseña.setText("<html><a href=''>¿Olvido la contraseña?</a></html>");
        lblOlvidoContraseña.setPreferredSize(new java.awt.Dimension(70, 17));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 63;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        pnlLogin.add(lblOlvidoContraseña, gridBagConstraints);

        btnCambiar.setBackground(new java.awt.Color(101, 158, 234));
        btnCambiar.setForeground(new java.awt.Color(51, 51, 51));
        btnCambiar.setText("CAMBIAR");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlLogin.add(btnCambiar, gridBagConstraints);

        lblEnlaceManualUsuario.setText("<html><a href=''>Manual de usuario</a></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        pnlLogin.add(lblEnlaceManualUsuario, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        pnlLogin.add(filler2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        pnlBody.add(pnlLogin, gridBagConstraints);

        getContentPane().add(pnlBody);

        PnlBottom.setBackground(java.awt.Color.white);
        PnlBottom.setPreferredSize(new java.awt.Dimension(400, 50));
        getContentPane().add(PnlBottom);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmContraseñaOlvidada().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlBottom;
    private javax.swing.JButton btnCambiar;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel lblContraseñaActual;
    private javax.swing.JLabel lblContraseñaConfirmar;
    private javax.swing.JLabel lblContraseñaNueva;
    private javax.swing.JLabel lblEnlaceManualUsuario;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblOlvidoContraseña;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPasswordField txtPasswordActual;
    private javax.swing.JPasswordField txtPasswordConfirmar;
    private javax.swing.JPasswordField txtPasswordNueva;
    // End of variables declaration//GEN-END:variables
}
