/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package s.z_talent_manager.vista;



/**
 *
 * @author maymansito
 */
public class FrmCompetenciaModificar extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCompetenciaModificar.class.getName());

    /**
     * Creates new form FrmExperienciaLaboralModificacion
     */
    
  
    
    
    public FrmCompetenciaModificar() {
    
    initComponents();
    jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
 
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlBody = new javax.swing.JPanel();
        lblCompetencia = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblCapacidadesTecnicas = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblCapacidadesTransversales = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblAutonomia = new javax.swing.JLabel();
        cmbAutonomia = new javax.swing.JComboBox<>();
        lblTrabajoEnEquipo = new javax.swing.JLabel();
        cmbTrabajoEnEquipo = new javax.swing.JComboBox<>();
        lblComunicacionEfectiva = new javax.swing.JLabel();
        cmbComunicacionEfectiva = new javax.swing.JComboBox<>();
        lblResolucionDeProblemas = new javax.swing.JLabel();
        cmbResolucionDeProblemas = new javax.swing.JComboBox<>();
        lblGestionDeTiempo = new javax.swing.JLabel();
        cmbGestionDeTiempo = new javax.swing.JComboBox<>();
        lblLiderazgo = new javax.swing.JLabel();
        cmbLiderazgo = new javax.swing.JComboBox<>();
        lblAdaptabilidad = new javax.swing.JLabel();
        cmbAdaptabilidad = new javax.swing.JComboBox<>();
        lblCreatividad = new javax.swing.JLabel();
        cmbCreatividad = new javax.swing.JComboBox<>();
        lblPensamientoCritico = new javax.swing.JLabel();
        cmbPensamientoCritico = new javax.swing.JComboBox<>();
        pnlFooter = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificar informacion personal");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 550));

        pnlBody.setBackground(new java.awt.Color(255, 255, 255));
        pnlBody.setPreferredSize(new java.awt.Dimension(800, 700));
        pnlBody.setLayout(new java.awt.GridBagLayout());

        lblCompetencia.setForeground(new java.awt.Color(51, 51, 51));
        lblCompetencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCompetencia.setText("Competencia");
        lblCompetencia.setPreferredSize(new java.awt.Dimension(800, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        pnlBody.add(lblCompetencia, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 400.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(jSeparator1, gridBagConstraints);

        lblCapacidadesTecnicas.setForeground(new java.awt.Color(51, 51, 51));
        lblCapacidadesTecnicas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCapacidadesTecnicas.setText("Capcidades tecnicas");
        lblCapacidadesTecnicas.setPreferredSize(new java.awt.Dimension(800, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(lblCapacidadesTecnicas, gridBagConstraints);

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(255, 0, 0));
        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 400.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(jSeparator2, gridBagConstraints);

        lblCapacidadesTransversales.setForeground(new java.awt.Color(51, 51, 51));
        lblCapacidadesTransversales.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCapacidadesTransversales.setText("Capacidades transversales");
        lblCapacidadesTransversales.setPreferredSize(new java.awt.Dimension(800, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(lblCapacidadesTransversales, gridBagConstraints);

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(255, 0, 0));
        jSeparator3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 400.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(jSeparator3, gridBagConstraints);

        lblAutonomia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAutonomia.setForeground(new java.awt.Color(7, 48, 26));
        lblAutonomia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAutonomia.setText("Autonomia");
        lblAutonomia.setPreferredSize(new java.awt.Dimension(350, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(lblAutonomia, gridBagConstraints);

        cmbAutonomia.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(cmbAutonomia, gridBagConstraints);

        lblTrabajoEnEquipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTrabajoEnEquipo.setForeground(new java.awt.Color(7, 48, 26));
        lblTrabajoEnEquipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTrabajoEnEquipo.setText("Trabajo en equipo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(lblTrabajoEnEquipo, gridBagConstraints);

        cmbTrabajoEnEquipo.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(cmbTrabajoEnEquipo, gridBagConstraints);

        lblComunicacionEfectiva.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblComunicacionEfectiva.setForeground(new java.awt.Color(7, 48, 26));
        lblComunicacionEfectiva.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblComunicacionEfectiva.setText("Trabajo en equipo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(lblComunicacionEfectiva, gridBagConstraints);

        cmbComunicacionEfectiva.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(cmbComunicacionEfectiva, gridBagConstraints);

        lblResolucionDeProblemas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblResolucionDeProblemas.setForeground(new java.awt.Color(7, 48, 26));
        lblResolucionDeProblemas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblResolucionDeProblemas.setText("Resolucion de problemas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(lblResolucionDeProblemas, gridBagConstraints);

        cmbResolucionDeProblemas.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 29;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(cmbResolucionDeProblemas, gridBagConstraints);

        lblGestionDeTiempo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGestionDeTiempo.setForeground(new java.awt.Color(7, 48, 26));
        lblGestionDeTiempo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGestionDeTiempo.setText("Gestion de tiempo");
        lblGestionDeTiempo.setMaximumSize(new java.awt.Dimension(63, 16));
        lblGestionDeTiempo.setMinimumSize(new java.awt.Dimension(63, 16));
        lblGestionDeTiempo.setPreferredSize(new java.awt.Dimension(63, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(lblGestionDeTiempo, gridBagConstraints);

        cmbGestionDeTiempo.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(cmbGestionDeTiempo, gridBagConstraints);

        lblLiderazgo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLiderazgo.setForeground(new java.awt.Color(7, 48, 26));
        lblLiderazgo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLiderazgo.setText("Liderazgo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(lblLiderazgo, gridBagConstraints);

        cmbLiderazgo.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(cmbLiderazgo, gridBagConstraints);

        lblAdaptabilidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAdaptabilidad.setForeground(new java.awt.Color(7, 48, 26));
        lblAdaptabilidad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAdaptabilidad.setText("Adaptabilidad");
        lblAdaptabilidad.setPreferredSize(new java.awt.Dimension(350, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(lblAdaptabilidad, gridBagConstraints);

        cmbAdaptabilidad.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(cmbAdaptabilidad, gridBagConstraints);

        lblCreatividad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCreatividad.setForeground(new java.awt.Color(7, 48, 26));
        lblCreatividad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCreatividad.setText("Creatividad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(lblCreatividad, gridBagConstraints);

        cmbCreatividad.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(cmbCreatividad, gridBagConstraints);

        lblPensamientoCritico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPensamientoCritico.setForeground(new java.awt.Color(7, 48, 26));
        lblPensamientoCritico.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPensamientoCritico.setText("Pensamiento critico");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(lblPensamientoCritico, gridBagConstraints);

        cmbPensamientoCritico.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlBody.add(cmbPensamientoCritico, gridBagConstraints);

        jScrollPane1.setViewportView(pnlBody);

        getContentPane().add(jScrollPane1);

        pnlFooter.setBackground(new java.awt.Color(255, 255, 255));
        pnlFooter.setPreferredSize(new java.awt.Dimension(800, 50));

        btnCancelar.setForeground(new java.awt.Color(51, 51, 51));
        btnCancelar.setText("CANCELAR");
        pnlFooter.add(btnCancelar);

        btnGuardar.setBackground(new java.awt.Color(7, 48, 26));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlFooter.add(btnGuardar);

        getContentPane().add(pnlFooter);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCompetenciaModificar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbAdaptabilidad;
    private javax.swing.JComboBox<String> cmbAutonomia;
    private javax.swing.JComboBox<String> cmbComunicacionEfectiva;
    private javax.swing.JComboBox<String> cmbCreatividad;
    private javax.swing.JComboBox<String> cmbGestionDeTiempo;
    private javax.swing.JComboBox<String> cmbLiderazgo;
    private javax.swing.JComboBox<String> cmbPensamientoCritico;
    private javax.swing.JComboBox<String> cmbResolucionDeProblemas;
    private javax.swing.JComboBox<String> cmbTrabajoEnEquipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAdaptabilidad;
    private javax.swing.JLabel lblAutonomia;
    private javax.swing.JLabel lblCapacidadesTecnicas;
    private javax.swing.JLabel lblCapacidadesTransversales;
    private javax.swing.JLabel lblCompetencia;
    private javax.swing.JLabel lblComunicacionEfectiva;
    private javax.swing.JLabel lblCreatividad;
    private javax.swing.JLabel lblGestionDeTiempo;
    private javax.swing.JLabel lblLiderazgo;
    private javax.swing.JLabel lblPensamientoCritico;
    private javax.swing.JLabel lblResolucionDeProblemas;
    private javax.swing.JLabel lblTrabajoEnEquipo;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlFooter;
    // End of variables declaration//GEN-END:variables
}
