/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package s.z_talent_manager.vista;

/**
 *
 * @author maymansito
 */
public class FrmCompetencia extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCompetencia.class.getName());

    /**
     * Creates new form FrmExperienciaLaboralModificacion
     */
    public FrmCompetencia() {
        initComponents();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlBody = new javax.swing.JPanel();
        lblIdiomas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstIdiomas = new javax.swing.JList<>();
        lblComprensionAuditiva = new javax.swing.JLabel();
        cmbComprensionAuditiva = new javax.swing.JComboBox<>();
        lblComprensionOral = new javax.swing.JLabel();
        cmbComprensionOral = new javax.swing.JComboBox<>();
        lblComprensionLectura = new javax.swing.JLabel();
        cmbComprensionLectura = new javax.swing.JComboBox<>();
        lblComprensionEscrita = new javax.swing.JLabel();
        cmbComprensionAuditiva1 = new javax.swing.JComboBox<>();
        lblIdioma = new javax.swing.JLabel();
        cmbIdioma = new javax.swing.JComboBox<>();
        pnlAñadirEliminarIdioma = new javax.swing.JPanel();
        btnEliminarIdioma = new javax.swing.JButton();
        btnGuardarIdioma = new javax.swing.JButton();
        lblCapacidadesTecnicas = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblCapacidadesTransversales = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblAutonomia = new javax.swing.JLabel();
        cmbAutonomia = new javax.swing.JComboBox<>();
        lblTrabajoEnEquipo = new javax.swing.JLabel();
        cmbTrabajoEnEquipo = new javax.swing.JComboBox<>();
        lblComunicacionEfectiva = new javax.swing.JLabel();
        cmbComunicacionEfectiva = new javax.swing.JComboBox<>();
        lblResolucionDeProblemas = new javax.swing.JLabel();
        cmbResolucionDeProblemas = new javax.swing.JComboBox<>();
        lblGestionDeTiempo = new javax.swing.JLabel();
        cmbGestionDeTiempo = new javax.swing.JComboBox<>();
        lblLiderazgo = new javax.swing.JLabel();
        cmbLiderazgo = new javax.swing.JComboBox<>();
        lblAdaptabilidad = new javax.swing.JLabel();
        cmbAdaptabilidad = new javax.swing.JComboBox<>();
        lblCreatividad = new javax.swing.JLabel();
        cmbCreatividad = new javax.swing.JComboBox<>();
        lblPensamientoCritico = new javax.swing.JLabel();
        cmbPensamientoCritico = new javax.swing.JComboBox<>();
        pnlFooter = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificar informacion personal");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 550));

        pnlBody.setBackground(new java.awt.Color(255, 255, 255));
        pnlBody.setPreferredSize(new java.awt.Dimension(800, 700));
        pnlBody.setLayout(new java.awt.GridBagLayout());

        lblIdiomas.setForeground(new java.awt.Color(51, 51, 51));
        lblIdiomas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIdiomas.setText("Idiomas");
        lblIdiomas.setPreferredSize(new java.awt.Dimension(800, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        pnlBody.add(lblIdiomas, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 400.0;
        pnlBody.add(jSeparator1, gridBagConstraints);

        jScrollPane2.setForeground(new java.awt.Color(51, 51, 51));

        lstIdiomas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstIdiomas.setPreferredSize(new java.awt.Dimension(300, 600));
        jScrollPane2.setViewportView(lstIdiomas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        pnlBody.add(jScrollPane2, gridBagConstraints);

        lblComprensionAuditiva.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblComprensionAuditiva.setForeground(new java.awt.Color(51, 51, 51));
        lblComprensionAuditiva.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblComprensionAuditiva.setText("Comprension auditiva");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlBody.add(lblComprensionAuditiva, gridBagConstraints);

        cmbComprensionAuditiva.setBackground(new java.awt.Color(255, 255, 255));
        cmbComprensionAuditiva.setForeground(new java.awt.Color(51, 51, 51));
        cmbComprensionAuditiva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        pnlBody.add(cmbComprensionAuditiva, gridBagConstraints);

        lblComprensionOral.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblComprensionOral.setForeground(new java.awt.Color(51, 51, 51));
        lblComprensionOral.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblComprensionOral.setText("Comprension oral");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlBody.add(lblComprensionOral, gridBagConstraints);

        cmbComprensionOral.setBackground(new java.awt.Color(255, 255, 255));
        cmbComprensionOral.setForeground(new java.awt.Color(51, 51, 51));
        cmbComprensionOral.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 400);
        pnlBody.add(cmbComprensionOral, gridBagConstraints);

        lblComprensionLectura.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblComprensionLectura.setForeground(new java.awt.Color(51, 51, 51));
        lblComprensionLectura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblComprensionLectura.setText("Comprension lectura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlBody.add(lblComprensionLectura, gridBagConstraints);

        cmbComprensionLectura.setBackground(new java.awt.Color(255, 255, 255));
        cmbComprensionLectura.setForeground(new java.awt.Color(51, 51, 51));
        cmbComprensionLectura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        pnlBody.add(cmbComprensionLectura, gridBagConstraints);

        lblComprensionEscrita.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblComprensionEscrita.setForeground(new java.awt.Color(51, 51, 51));
        lblComprensionEscrita.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblComprensionEscrita.setText("Comprension escrita");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlBody.add(lblComprensionEscrita, gridBagConstraints);

        cmbComprensionAuditiva1.setBackground(new java.awt.Color(255, 255, 255));
        cmbComprensionAuditiva1.setForeground(new java.awt.Color(51, 51, 51));
        cmbComprensionAuditiva1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 400);
        pnlBody.add(cmbComprensionAuditiva1, gridBagConstraints);

        lblIdioma.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIdioma.setForeground(new java.awt.Color(51, 51, 51));
        lblIdioma.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIdioma.setText("Idioma");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlBody.add(lblIdioma, gridBagConstraints);

        cmbIdioma.setBackground(new java.awt.Color(255, 255, 255));
        cmbIdioma.setForeground(new java.awt.Color(51, 51, 51));
        cmbIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        pnlBody.add(cmbIdioma, gridBagConstraints);

        pnlAñadirEliminarIdioma.setBackground(new java.awt.Color(255, 255, 255));
        pnlAñadirEliminarIdioma.setPreferredSize(new java.awt.Dimension(800, 50));

        btnEliminarIdioma.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarIdioma.setForeground(new java.awt.Color(51, 51, 51));
        btnEliminarIdioma.setText("Eliminar");
        pnlAñadirEliminarIdioma.add(btnEliminarIdioma);

        btnGuardarIdioma.setBackground(new java.awt.Color(78, 125, 158));
        btnGuardarIdioma.setForeground(new java.awt.Color(51, 51, 51));
        btnGuardarIdioma.setText("Añadir");
        pnlAñadirEliminarIdioma.add(btnGuardarIdioma);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 320, 0, 0);
        pnlBody.add(pnlAñadirEliminarIdioma, gridBagConstraints);

        lblCapacidadesTecnicas.setForeground(new java.awt.Color(51, 51, 51));
        lblCapacidadesTecnicas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCapacidadesTecnicas.setText("Capcidades tecnicas");
        lblCapacidadesTecnicas.setPreferredSize(new java.awt.Dimension(800, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        pnlBody.add(lblCapacidadesTecnicas, gridBagConstraints);

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(255, 0, 0));
        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 400.0;
        pnlBody.add(jSeparator2, gridBagConstraints);

        lblCapacidadesTransversales.setForeground(new java.awt.Color(51, 51, 51));
        lblCapacidadesTransversales.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCapacidadesTransversales.setText("Capacidades transversales");
        lblCapacidadesTransversales.setPreferredSize(new java.awt.Dimension(800, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        pnlBody.add(lblCapacidadesTransversales, gridBagConstraints);

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(255, 0, 0));
        jSeparator3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 400.0;
        pnlBody.add(jSeparator3, gridBagConstraints);

        lblAutonomia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAutonomia.setForeground(new java.awt.Color(51, 51, 51));
        lblAutonomia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAutonomia.setText("Autonomia");
        lblAutonomia.setPreferredSize(new java.awt.Dimension(350, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlBody.add(lblAutonomia, gridBagConstraints);

        cmbAutonomia.setBackground(new java.awt.Color(255, 255, 255));
        cmbAutonomia.setForeground(new java.awt.Color(51, 51, 51));
        cmbAutonomia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 400);
        pnlBody.add(cmbAutonomia, gridBagConstraints);

        lblTrabajoEnEquipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTrabajoEnEquipo.setForeground(new java.awt.Color(51, 51, 51));
        lblTrabajoEnEquipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTrabajoEnEquipo.setText("Trabajo en equipo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlBody.add(lblTrabajoEnEquipo, gridBagConstraints);

        cmbTrabajoEnEquipo.setBackground(new java.awt.Color(255, 255, 255));
        cmbTrabajoEnEquipo.setForeground(new java.awt.Color(51, 51, 51));
        cmbTrabajoEnEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 400);
        pnlBody.add(cmbTrabajoEnEquipo, gridBagConstraints);

        lblComunicacionEfectiva.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblComunicacionEfectiva.setForeground(new java.awt.Color(51, 51, 51));
        lblComunicacionEfectiva.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblComunicacionEfectiva.setText("Trabajo en equipo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlBody.add(lblComunicacionEfectiva, gridBagConstraints);

        cmbComunicacionEfectiva.setBackground(new java.awt.Color(255, 255, 255));
        cmbComunicacionEfectiva.setForeground(new java.awt.Color(51, 51, 51));
        cmbComunicacionEfectiva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 400);
        pnlBody.add(cmbComunicacionEfectiva, gridBagConstraints);

        lblResolucionDeProblemas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblResolucionDeProblemas.setForeground(new java.awt.Color(51, 51, 51));
        lblResolucionDeProblemas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblResolucionDeProblemas.setText("Resolucion de problemas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlBody.add(lblResolucionDeProblemas, gridBagConstraints);

        cmbResolucionDeProblemas.setBackground(new java.awt.Color(255, 255, 255));
        cmbResolucionDeProblemas.setForeground(new java.awt.Color(51, 51, 51));
        cmbResolucionDeProblemas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 29;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 400);
        pnlBody.add(cmbResolucionDeProblemas, gridBagConstraints);

        lblGestionDeTiempo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGestionDeTiempo.setForeground(new java.awt.Color(51, 51, 51));
        lblGestionDeTiempo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGestionDeTiempo.setText("Gestion de tiempo");
        lblGestionDeTiempo.setMaximumSize(new java.awt.Dimension(63, 16));
        lblGestionDeTiempo.setMinimumSize(new java.awt.Dimension(63, 16));
        lblGestionDeTiempo.setPreferredSize(new java.awt.Dimension(63, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlBody.add(lblGestionDeTiempo, gridBagConstraints);

        cmbGestionDeTiempo.setBackground(new java.awt.Color(255, 255, 255));
        cmbGestionDeTiempo.setForeground(new java.awt.Color(51, 51, 51));
        cmbGestionDeTiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 400);
        pnlBody.add(cmbGestionDeTiempo, gridBagConstraints);

        lblLiderazgo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLiderazgo.setForeground(new java.awt.Color(51, 51, 51));
        lblLiderazgo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLiderazgo.setText("Liderazgo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlBody.add(lblLiderazgo, gridBagConstraints);

        cmbLiderazgo.setBackground(new java.awt.Color(255, 255, 255));
        cmbLiderazgo.setForeground(new java.awt.Color(51, 51, 51));
        cmbLiderazgo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 400);
        pnlBody.add(cmbLiderazgo, gridBagConstraints);

        lblAdaptabilidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAdaptabilidad.setForeground(new java.awt.Color(51, 51, 51));
        lblAdaptabilidad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAdaptabilidad.setText("Adaptabilidad");
        lblAdaptabilidad.setPreferredSize(new java.awt.Dimension(350, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlBody.add(lblAdaptabilidad, gridBagConstraints);

        cmbAdaptabilidad.setBackground(new java.awt.Color(255, 255, 255));
        cmbAdaptabilidad.setForeground(new java.awt.Color(51, 51, 51));
        cmbAdaptabilidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 400);
        pnlBody.add(cmbAdaptabilidad, gridBagConstraints);

        lblCreatividad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCreatividad.setForeground(new java.awt.Color(51, 51, 51));
        lblCreatividad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCreatividad.setText("Creatividad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlBody.add(lblCreatividad, gridBagConstraints);

        cmbCreatividad.setBackground(new java.awt.Color(255, 255, 255));
        cmbCreatividad.setForeground(new java.awt.Color(51, 51, 51));
        cmbCreatividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 400);
        pnlBody.add(cmbCreatividad, gridBagConstraints);

        lblPensamientoCritico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPensamientoCritico.setForeground(new java.awt.Color(51, 51, 51));
        lblPensamientoCritico.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPensamientoCritico.setText("Pensamiento critico");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlBody.add(lblPensamientoCritico, gridBagConstraints);

        cmbPensamientoCritico.setBackground(new java.awt.Color(255, 255, 255));
        cmbPensamientoCritico.setForeground(new java.awt.Color(51, 51, 51));
        cmbPensamientoCritico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 400);
        pnlBody.add(cmbPensamientoCritico, gridBagConstraints);

        jScrollPane1.setViewportView(pnlBody);

        getContentPane().add(jScrollPane1);

        pnlFooter.setBackground(new java.awt.Color(255, 255, 255));
        pnlFooter.setPreferredSize(new java.awt.Dimension(800, 50));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setForeground(new java.awt.Color(51, 51, 51));
        btnCancelar.setText("CANCELAR");
        pnlFooter.add(btnCancelar);

        btnGuardar.setBackground(new java.awt.Color(78, 125, 158));
        btnGuardar.setForeground(new java.awt.Color(51, 51, 51));
        btnGuardar.setText("GUARDAR");
        pnlFooter.add(btnGuardar);

        getContentPane().add(pnlFooter);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCompetencia().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminarIdioma;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarIdioma;
    private javax.swing.JComboBox<String> cmbAdaptabilidad;
    private javax.swing.JComboBox<String> cmbAutonomia;
    private javax.swing.JComboBox<String> cmbComprensionAuditiva;
    private javax.swing.JComboBox<String> cmbComprensionAuditiva1;
    private javax.swing.JComboBox<String> cmbComprensionLectura;
    private javax.swing.JComboBox<String> cmbComprensionOral;
    private javax.swing.JComboBox<String> cmbComunicacionEfectiva;
    private javax.swing.JComboBox<String> cmbCreatividad;
    private javax.swing.JComboBox<String> cmbGestionDeTiempo;
    private javax.swing.JComboBox<String> cmbIdioma;
    private javax.swing.JComboBox<String> cmbLiderazgo;
    private javax.swing.JComboBox<String> cmbPensamientoCritico;
    private javax.swing.JComboBox<String> cmbResolucionDeProblemas;
    private javax.swing.JComboBox<String> cmbTrabajoEnEquipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAdaptabilidad;
    private javax.swing.JLabel lblAutonomia;
    private javax.swing.JLabel lblCapacidadesTecnicas;
    private javax.swing.JLabel lblCapacidadesTransversales;
    private javax.swing.JLabel lblComprensionAuditiva;
    private javax.swing.JLabel lblComprensionEscrita;
    private javax.swing.JLabel lblComprensionLectura;
    private javax.swing.JLabel lblComprensionOral;
    private javax.swing.JLabel lblComunicacionEfectiva;
    private javax.swing.JLabel lblCreatividad;
    private javax.swing.JLabel lblGestionDeTiempo;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblIdiomas;
    private javax.swing.JLabel lblLiderazgo;
    private javax.swing.JLabel lblPensamientoCritico;
    private javax.swing.JLabel lblResolucionDeProblemas;
    private javax.swing.JLabel lblTrabajoEnEquipo;
    private javax.swing.JList<String> lstIdiomas;
    private javax.swing.JPanel pnlAñadirEliminarIdioma;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlFooter;
    // End of variables declaration//GEN-END:variables
}
