/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package s.z_talent_manager.vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import s.z_talent_manager.modelo.Candidato;
import s.z_talent_manager.modelo.Experiencia;
import s.z_talent_manager.modelo.Sesion;
import s.z_talent_manager.servicio.ZTalentManagerServicio;

/**
 *
 * @author maymansito
 */
public class FrmExperienciaLaboralModificacion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmExperienciaLaboralModificacion.class.getName());

    /**
     * Creates new form FrmExperienciaLaboralModificacion
     */
    public FrmExperienciaLaboralModificacion() {
        initComponents();
        setTitle("Añadir Experiencia Laboral");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlBody = new javax.swing.JPanel();
        lblExperienciaLaboral = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblPuestoOcupado = new javax.swing.JLabel();
        txtPuesto = new javax.swing.JTextField();
        lblCompañia = new javax.swing.JLabel();
        txtCompañia = new javax.swing.JTextField();
        lblFechaInicio = new javax.swing.JLabel();
        txtFechaInicioLaboral = new javax.swing.JFormattedTextField();
        lblFechaFinalizacion = new javax.swing.JLabel();
        lblPrincipalesActividades = new javax.swing.JLabel();
        txtFechaFinLaboral = new javax.swing.JFormattedTextField();
        txaActividades = new javax.swing.JTextArea();
        rbtnEnCursoLaboral = new javax.swing.JRadioButton();
        pnlFooter = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificar experiencia laboral");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        pnlBody.setBackground(new java.awt.Color(255, 255, 255));
        pnlBody.setPreferredSize(new java.awt.Dimension(800, 550));
        pnlBody.setLayout(new java.awt.GridBagLayout());

        lblExperienciaLaboral.setForeground(new java.awt.Color(51, 51, 51));
        lblExperienciaLaboral.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblExperienciaLaboral.setText("Experiencia laboral");
        lblExperienciaLaboral.setPreferredSize(new java.awt.Dimension(800, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        pnlBody.add(lblExperienciaLaboral, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 400.0;
        pnlBody.add(jSeparator1, gridBagConstraints);

        lblPuestoOcupado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPuestoOcupado.setForeground(new java.awt.Color(7, 48, 26));
        lblPuestoOcupado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPuestoOcupado.setText("Puesto o cargo ocupado  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlBody.add(lblPuestoOcupado, gridBagConstraints);

        txtPuesto.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 400);
        pnlBody.add(txtPuesto, gridBagConstraints);

        lblCompañia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCompañia.setForeground(new java.awt.Color(7, 48, 26));
        lblCompañia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCompañia.setText("Compañia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        pnlBody.add(lblCompañia, gridBagConstraints);

        txtCompañia.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 400);
        pnlBody.add(txtCompañia, gridBagConstraints);

        lblFechaInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFechaInicio.setForeground(new java.awt.Color(7, 48, 26));
        lblFechaInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFechaInicio.setText("Fecha de inicio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlBody.add(lblFechaInicio, gridBagConstraints);

        txtFechaInicioLaboral.setForeground(new java.awt.Color(51, 51, 51));
        txtFechaInicioLaboral.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtFechaInicioLaboral.setText("02/02/02");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 0, 0);
        pnlBody.add(txtFechaInicioLaboral, gridBagConstraints);

        lblFechaFinalizacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFechaFinalizacion.setForeground(new java.awt.Color(7, 48, 26));
        lblFechaFinalizacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFechaFinalizacion.setText("Fecha de finalizacion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlBody.add(lblFechaFinalizacion, gridBagConstraints);

        lblPrincipalesActividades.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrincipalesActividades.setForeground(new java.awt.Color(7, 48, 26));
        lblPrincipalesActividades.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrincipalesActividades.setText("Principales actividades y responsabilidades");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlBody.add(lblPrincipalesActividades, gridBagConstraints);

        txtFechaFinLaboral.setForeground(new java.awt.Color(51, 51, 51));
        txtFechaFinLaboral.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtFechaFinLaboral.setText("02/02/02");
        txtFechaFinLaboral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaFinLaboralActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 0, 0);
        pnlBody.add(txtFechaFinLaboral, gridBagConstraints);

        txaActividades.setColumns(20);
        txaActividades.setForeground(new java.awt.Color(7, 48, 26));
        txaActividades.setRows(5);
        txaActividades.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txaActividades.setMinimumSize(new java.awt.Dimension(300, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 0, 0);
        pnlBody.add(txaActividades, gridBagConstraints);

        rbtnEnCursoLaboral.setBackground(new java.awt.Color(255, 255, 255));
        rbtnEnCursoLaboral.setForeground(new java.awt.Color(51, 51, 51));
        rbtnEnCursoLaboral.setText("En curso");
        rbtnEnCursoLaboral.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 400);
        pnlBody.add(rbtnEnCursoLaboral, gridBagConstraints);

        getContentPane().add(pnlBody);

        pnlFooter.setBackground(new java.awt.Color(255, 255, 255));
        pnlFooter.setPreferredSize(new java.awt.Dimension(800, 50));

        btnCancelar.setForeground(new java.awt.Color(7, 48, 26));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlFooter.add(btnCancelar);

        btnGuardar.setBackground(new java.awt.Color(7, 48, 26));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlFooter.add(btnGuardar);

        getContentPane().add(pnlFooter);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaFinLaboralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaFinLaboralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaFinLaboralActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

 try {
        // ── Leer desde BD, no desde Sesion ───────────────────────
        Integer idCandidato = ((Candidato) Sesion.getUsuario()).getIdUsuario();
        Candidato c = ZTalentManagerServicio.getServicio().getCandidato(idCandidato);

        Experiencia nuevaExp = new Experiencia();
        nuevaExp.setCompañia(txtCompañia.getText().trim());
        nuevaExp.setPuesto(txtPuesto.getText().trim());
        nuevaExp.setDescripcion(txaActividades.getText().trim());

        if (txtFechaInicioLaboral.getValue() != null) {
            java.util.Date fecha = (java.util.Date) txtFechaInicioLaboral.getValue();
            java.util.Calendar cal = java.util.Calendar.getInstance();
            cal.setTime(fecha);
            nuevaExp.setFechaInicio(java.time.LocalDate.of(
                cal.get(java.util.Calendar.YEAR),
                cal.get(java.util.Calendar.MONTH) + 1,
                cal.get(java.util.Calendar.DAY_OF_MONTH)
            ));
        }

        if (txtFechaFinLaboral.getValue() != null) {
            java.util.Date fecha = (java.util.Date) txtFechaFinLaboral.getValue();
            java.util.Calendar cal = java.util.Calendar.getInstance();
            cal.setTime(fecha);
            nuevaExp.setFechaFin(java.time.LocalDate.of(
                cal.get(java.util.Calendar.YEAR),
                cal.get(java.util.Calendar.MONTH) + 1,
                cal.get(java.util.Calendar.DAY_OF_MONTH)
            ));
        }

        nuevaExp.setCandidato(c);

        if (c.getExperiencias() == null) {
            c.setExperiencias(new ArrayList<>());
        }
        c.getExperiencias().add(nuevaExp);

        // ── Persistir ─────────────────────────────────────────────
        ZTalentManagerServicio.getServicio().modificarCandidato(c);

        // ── Actualizar sesión con datos frescos desde BD ──────────
        Candidato actualizado = ZTalentManagerServicio.getServicio()
                .getCandidato(idCandidato);
        Sesion.setUsuario(actualizado);

        JOptionPane.showMessageDialog(this, "Datos guardados correctamente");
        dispose();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
            "Error al guardar: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmExperienciaLaboralModificacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCompañia;
    private javax.swing.JLabel lblExperienciaLaboral;
    private javax.swing.JLabel lblFechaFinalizacion;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblPrincipalesActividades;
    private javax.swing.JLabel lblPuestoOcupado;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JRadioButton rbtnEnCursoLaboral;
    private javax.swing.JTextArea txaActividades;
    private javax.swing.JTextField txtCompañia;
    private javax.swing.JFormattedTextField txtFechaFinLaboral;
    private javax.swing.JFormattedTextField txtFechaInicioLaboral;
    private javax.swing.JTextField txtPuesto;
    // End of variables declaration//GEN-END:variables
}
