/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package s.z_talent_manager.vista;

import java.awt.Cursor;
import java.awt.Desktop;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URI;
import javax.swing.JOptionPane;
import s.z_talent_manager.modelo.Sesion;
import s.z_talent_manager.modelo.Usuario;
import s.z_talent_manager.servicio.ZTalentManagerServicio;

/**
 *
 * @author maymansito
 */
public class FrmLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmLogin.class.getName());

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        setLocationRelativeTo(null);
        
        tbtnVerContraseña.addActionListener(e -> {
    if (tbtnVerContraseña.isSelected()) {
        txtPassword.setEchoChar((char) 0); // muestra el texto
    } else {
        txtPassword.setEchoChar('•'); // vuelve a ocultar
    }
});

        // sirve para al hacer click en el hipervinculo  redirija a la pagina   
        lblEnlaceManualUsuario.setCursor(new Cursor(Cursor.HAND_CURSOR));
        txtUsuario.setRequestFocusEnabled(true);
        lblEnlaceManualUsuario.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    java.net.URL url = getClass().getResource("/manual/manualUsuario.html");
                    Desktop.getDesktop().browse(url.toURI());
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });

        btnLogin.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {

            }
        });

        lblOlvidoContraseña.setCursor(new Cursor(Cursor.HAND_CURSOR));

        lblOlvidoContraseña.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {

                try {
                    Desktop.getDesktop().browse(new URI("https://forms.gle/WU8BtuFxXNNqvkcm7"));
                } catch (Exception ex) {
                    ex.printStackTrace();
                }

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlHeader = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblOlvidoContraseña = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        tbtnVerContraseña = new javax.swing.JToggleButton();
        PnlBottom = new javax.swing.JPanel();
        lblEnlaceManualUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Z_Talent Manager");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        pnlHeader.setBackground(java.awt.Color.white);
        pnlHeader.setPreferredSize(new java.awt.Dimension(800, 200));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        lblLogo.setToolTipText("");
        pnlHeader.add(lblLogo);

        getContentPane().add(pnlHeader);

        pnlBody.setBackground(java.awt.Color.white);
        pnlBody.setPreferredSize(new java.awt.Dimension(800, 350));
        pnlBody.setLayout(new java.awt.GridBagLayout());

        pnlLogin.setBackground(new java.awt.Color(51, 153, 102));
        pnlLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlLogin.setMaximumSize(new java.awt.Dimension(200, 100));
        pnlLogin.setPreferredSize(new java.awt.Dimension(500, 300));
        pnlLogin.setLayout(new java.awt.GridBagLayout());

        lblUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblUsuario.setText("USUARIO:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlLogin.add(lblUsuario, gridBagConstraints);

        txtUsuario.setForeground(new java.awt.Color(7, 48, 26));
        txtUsuario.setText("Usuario");
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsuario.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlLogin.add(txtUsuario, gridBagConstraints);

        lblContraseña.setForeground(new java.awt.Color(7, 48, 26));
        lblContraseña.setText("CONTRASEÑA:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlLogin.add(lblContraseña, gridBagConstraints);

        txtPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtPassword.setText("Contraseña");
        txtPassword.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlLogin.add(txtPassword, gridBagConstraints);

        lblOlvidoContraseña.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOlvidoContraseña.setText("<html><a href=''>¿Olvido la contraseña?</a></html>");
        lblOlvidoContraseña.setPreferredSize(new java.awt.Dimension(70, 17));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 63;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlLogin.add(lblOlvidoContraseña, gridBagConstraints);

        btnLogin.setBackground(new java.awt.Color(7, 48, 26));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlLogin.add(btnLogin, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        pnlLogin.add(filler2, gridBagConstraints);

        tbtnVerContraseña.setBackground(new java.awt.Color(51, 153, 102));
        tbtnVerContraseña.setForeground(new java.awt.Color(255, 255, 255));
        tbtnVerContraseña.setText("Ver");
        tbtnVerContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnVerContraseñaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        pnlLogin.add(tbtnVerContraseña, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        pnlBody.add(pnlLogin, gridBagConstraints);

        getContentPane().add(pnlBody);

        PnlBottom.setBackground(java.awt.Color.white);
        PnlBottom.setPreferredSize(new java.awt.Dimension(400, 50));

        lblEnlaceManualUsuario.setText("<html><a href=''>Manual de usuario</a></html>");
        PnlBottom.add(lblEnlaceManualUsuario);

        getContentPane().add(PnlBottom);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        String email = txtUsuario.getText();
        String password = new String(txtPassword.getPassword());

        try {

            Usuario usuario = ZTalentManagerServicio.getServicio().login(email, password);

            if (usuario != null) {
                Sesion.setUsuario(usuario);

                if (!Boolean.TRUE.equals(usuario.getAdministrador())) {
                    new FrmVentanaPrincipal().setVisible(true);
                } else {
                    new FrmPanelAdmin().setVisible(true);
                    System.out.println("Es administrador");
                }

                dispose();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Email o contraseña incorrectos",
                        "Login Fallido",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            // Errores inesperados (conexión BD, etc.)
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    
                    this,
                    "Error de conexión: " + e.getMessage(),
                    "ERROR", JOptionPane.WARNING_MESSAGE);
            
        }


    }//GEN-LAST:event_btnLoginActionPerformed

    private void tbtnVerContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnVerContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnVerContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlBottom;
    private javax.swing.JButton btnLogin;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblEnlaceManualUsuario;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblOlvidoContraseña;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JToggleButton tbtnVerContraseña;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
