/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package s.z_talent_manager.vista;

/**
 *
 * @author DAW1
 */
public class FrmPanelAdmin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPanelAdmin.class.getName());

    /**
     * Creates new form Prueba2
     */
    public FrmPanelAdmin() {
        initComponents();

        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Pantalla completa
        // Hacer el layout responsivo
        pnlPrincipal.setPreferredSize(null);
        // Hacer que pnlPrincipal ocupe todo el contenido
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlPrincipal, java.awt.BorderLayout.CENTER);

        pnlPrincipal.setPreferredSize(null); // Quitar tamaño fijo
        // Busca esta línea en initComponents y cámbiala a mano en el constructor:
        pnlContenido.setPreferredSize(null); // Elimina el Dimension(0, 450) fijo
        pnlHeader.setPreferredSize(null); // Elimina el Dimension(1100, 90) fijo

        // Placeholder "Search..."
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtSearch.getText().equals("Search...")) {
                    txtSearch.setText("");
                    txtSearch.setForeground(new java.awt.Color(7, 48, 26));
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtSearch.getText().isBlank()) {
                    txtSearch.setText("Search...");
                    txtSearch.setForeground(new java.awt.Color(74, 122, 96));
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnContr = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        pnlCentral = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();
        pnlCrearCandidato = new javax.swing.JPanel();
        bntCrearCandidato = new javax.swing.JButton();
        pnlBusqueda = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        pnlContenido = new javax.swing.JPanel();
        pnlFiltros = new javax.swing.JPanel();
        pnlCompTec = new javax.swing.JPanel();
        lblCompTec = new javax.swing.JLabel();
        pnlDesarrollo = new javax.swing.JPanel();
        tglJavaScript = new javax.swing.JToggleButton();
        tglPython = new javax.swing.JToggleButton();
        tglReact = new javax.swing.JToggleButton();
        tglNoode = new javax.swing.JToggleButton();
        tglJavaSql = new javax.swing.JToggleButton();
        tglApache = new javax.swing.JToggleButton();
        tglAws = new javax.swing.JToggleButton();
        tglKubernetes = new javax.swing.JToggleButton();
        tglLinux = new javax.swing.JToggleButton();
        tglDocker = new javax.swing.JToggleButton();
        pnlDiseño = new javax.swing.JPanel();
        tglFigma = new javax.swing.JToggleButton();
        tglAdobe = new javax.swing.JToggleButton();
        tglCss = new javax.swing.JToggleButton();
        tglGoogle = new javax.swing.JToggleButton();
        tglMeta = new javax.swing.JToggleButton();
        tglAds = new javax.swing.JToggleButton();
        pnlIdioma = new javax.swing.JPanel();
        lblIdioma = new javax.swing.JLabel();
        pnlIdiomas = new javax.swing.JPanel();
        chkEusk = new javax.swing.JCheckBox();
        chkCast = new javax.swing.JCheckBox();
        chkIng = new javax.swing.JCheckBox();
        chkFra = new javax.swing.JCheckBox();
        chkAle = new javax.swing.JCheckBox();
        pnlTituloTr = new javax.swing.JPanel();
        lblTransversales = new javax.swing.JLabel();
        pnlTransversales = new javax.swing.JPanel();
        chkAutnomia = new javax.swing.JCheckBox();
        chkCompromiso = new javax.swing.JCheckBox();
        chkImpl = new javax.swing.JCheckBox();
        chkImpl1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaContenidos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(211, 254, 234));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(211, 254, 234));
        pnlHeader.setPreferredSize(new java.awt.Dimension(1100, 90));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        pnlLogo.setBackground(new java.awt.Color(211, 254, 234));

        lblLogo.setBackground(new java.awt.Color(211, 254, 234));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        lblLogo.setPreferredSize(new java.awt.Dimension(400, 85));
        pnlLogo.add(lblLogo);

        pnlHeader.add(pnlLogo, java.awt.BorderLayout.WEST);

        pnlBotones.setBackground(new java.awt.Color(211, 254, 234));
        pnlBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnContr.setBackground(new java.awt.Color(211, 254, 234));
        btnContr.setForeground(new java.awt.Color(7, 48, 26));
        btnContr.setText("CAMBIAR CONTRASEÑA");
        btnContr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContr.setFocusPainted(false);
        btnContr.setPreferredSize(new java.awt.Dimension(180, 35));
        btnContr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContrActionPerformed(evt);
            }
        });
        pnlBotones.add(btnContr);

        btnSalir.setBackground(new java.awt.Color(211, 254, 234));
        btnSalir.setForeground(new java.awt.Color(7, 48, 26));
        btnSalir.setText("↪");
        btnSalir.setFocusPainted(false);
        btnSalir.setPreferredSize(new java.awt.Dimension(40, 35));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlBotones.add(btnSalir);

        pnlHeader.add(pnlBotones, java.awt.BorderLayout.EAST);

        pnlPrincipal.add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlCentral.setBackground(new java.awt.Color(211, 254, 234));
        pnlCentral.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 30, 10, 30));
        pnlCentral.setLayout(new java.awt.BorderLayout());

        lblBienvenida.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(7, 48, 26));
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("!Bienvenida/o, Admin!");
        lblBienvenida.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblBienvenida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlCentral.add(lblBienvenida, java.awt.BorderLayout.NORTH);

        pnlCrearCandidato.setBackground(new java.awt.Color(211, 254, 234));
        pnlCrearCandidato.setPreferredSize(new java.awt.Dimension(0, 45));

        bntCrearCandidato.setBackground(new java.awt.Color(51, 153, 102));
        bntCrearCandidato.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        bntCrearCandidato.setForeground(new java.awt.Color(255, 255, 255));
        bntCrearCandidato.setText("Crear Candidato");
        bntCrearCandidato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntCrearCandidato.setFocusPainted(false);
        bntCrearCandidato.setPreferredSize(new java.awt.Dimension(140, 34));
        bntCrearCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCrearCandidatoActionPerformed(evt);
            }
        });
        pnlCrearCandidato.add(bntCrearCandidato);

        pnlBusqueda.setBackground(new java.awt.Color(211, 254, 234));
        pnlBusqueda.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));

        txtSearch.setBackground(new java.awt.Color(248, 253, 249));
        txtSearch.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(74, 122, 96));
        txtSearch.setText("Search...");
        txtSearch.setFocusTraversalPolicyProvider(true);
        txtSearch.setPreferredSize(new java.awt.Dimension(700, 36));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        pnlBusqueda.add(txtSearch);

        btnBuscar.setBackground(new java.awt.Color(51, 153, 102));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("🔍");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setFocusPainted(false);
        btnBuscar.setPreferredSize(new java.awt.Dimension(42, 36));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        pnlBusqueda.add(btnBuscar);

        pnlCrearCandidato.add(pnlBusqueda);

        pnlCentral.add(pnlCrearCandidato, java.awt.BorderLayout.CENTER);

        pnlContenido.setBackground(new java.awt.Color(211, 254, 234));
        pnlContenido.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 10, 20));
        pnlContenido.setPreferredSize(new java.awt.Dimension(0, 450));
        pnlContenido.setLayout(new java.awt.BorderLayout());

        pnlFiltros.setBackground(new java.awt.Color(244, 253, 248));
        pnlFiltros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 240, 212)));
        pnlFiltros.setPreferredSize(new java.awt.Dimension(220, 0));
        pnlFiltros.setLayout(new javax.swing.BoxLayout(pnlFiltros, javax.swing.BoxLayout.Y_AXIS));

        pnlCompTec.setBackground(new java.awt.Color(244, 253, 248));
        pnlCompTec.setLayout(new java.awt.BorderLayout());

        lblCompTec.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lblCompTec.setForeground(new java.awt.Color(7, 48, 26));
        lblCompTec.setText("Competencia Técnica");
        pnlCompTec.add(lblCompTec, java.awt.BorderLayout.NORTH);

        pnlDesarrollo.setBackground(new java.awt.Color(244, 253, 248));
        pnlDesarrollo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Desarrollo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 13), new java.awt.Color(42, 74, 56))); // NOI18N
        pnlDesarrollo.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        pnlDesarrollo.setLayout(new java.awt.GridLayout(0, 2, 3, 3));

        tglJavaScript.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tglJavaScript.setForeground(new java.awt.Color(42, 74, 56));
        tglJavaScript.setText("JavaScript");
        tglJavaScript.setPreferredSize(new java.awt.Dimension(40, 15));
        tglJavaScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglJavaScriptActionPerformed(evt);
            }
        });
        pnlDesarrollo.add(tglJavaScript);

        tglPython.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tglPython.setForeground(new java.awt.Color(42, 74, 56));
        tglPython.setText("Python");
        tglPython.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglPythonActionPerformed(evt);
            }
        });
        pnlDesarrollo.add(tglPython);

        tglReact.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tglReact.setForeground(new java.awt.Color(42, 74, 56));
        tglReact.setText("React");
        tglReact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglReactActionPerformed(evt);
            }
        });
        pnlDesarrollo.add(tglReact);

        tglNoode.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tglNoode.setForeground(new java.awt.Color(42, 74, 56));
        tglNoode.setText("Noode.js");
        tglNoode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglNoodeActionPerformed(evt);
            }
        });
        pnlDesarrollo.add(tglNoode);

        tglJavaSql.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tglJavaSql.setForeground(new java.awt.Color(42, 74, 56));
        tglJavaSql.setText("SQL");
        tglJavaSql.setPreferredSize(new java.awt.Dimension(40, 15));
        tglJavaSql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglJavaSqlActionPerformed(evt);
            }
        });
        pnlDesarrollo.add(tglJavaSql);

        tglApache.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tglApache.setForeground(new java.awt.Color(42, 74, 56));
        tglApache.setText("Apache Spark");
        tglApache.setPreferredSize(new java.awt.Dimension(40, 15));
        tglApache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglApacheActionPerformed(evt);
            }
        });
        pnlDesarrollo.add(tglApache);

        tglAws.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tglAws.setForeground(new java.awt.Color(42, 74, 56));
        tglAws.setText("AWS");
        tglAws.setPreferredSize(new java.awt.Dimension(40, 15));
        tglAws.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglAwsActionPerformed(evt);
            }
        });
        pnlDesarrollo.add(tglAws);

        tglKubernetes.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tglKubernetes.setForeground(new java.awt.Color(42, 74, 56));
        tglKubernetes.setText("Kubernetes");
        tglKubernetes.setPreferredSize(new java.awt.Dimension(40, 15));
        tglKubernetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglKubernetesActionPerformed(evt);
            }
        });
        pnlDesarrollo.add(tglKubernetes);

        tglLinux.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tglLinux.setForeground(new java.awt.Color(42, 74, 56));
        tglLinux.setText("Linux");
        tglLinux.setPreferredSize(new java.awt.Dimension(40, 15));
        tglLinux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglLinuxActionPerformed(evt);
            }
        });
        pnlDesarrollo.add(tglLinux);

        tglDocker.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tglDocker.setForeground(new java.awt.Color(42, 74, 56));
        tglDocker.setText("Docker");
        tglDocker.setPreferredSize(new java.awt.Dimension(40, 15));
        tglDocker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglDockerActionPerformed(evt);
            }
        });
        pnlDesarrollo.add(tglDocker);

        pnlCompTec.add(pnlDesarrollo, java.awt.BorderLayout.CENTER);

        pnlDiseño.setBackground(new java.awt.Color(244, 253, 248));
        pnlDiseño.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Diseño", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 13), new java.awt.Color(42, 74, 56))); // NOI18N
        pnlDiseño.setForeground(new java.awt.Color(42, 74, 56));
        pnlDiseño.setFocusable(false);
        pnlDiseño.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        pnlDiseño.setLayout(new java.awt.GridLayout(0, 2, 3, 3));

        tglFigma.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tglFigma.setForeground(new java.awt.Color(42, 74, 56));
        tglFigma.setText("Figma");
        tglFigma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglFigmaActionPerformed(evt);
            }
        });
        pnlDiseño.add(tglFigma);

        tglAdobe.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tglAdobe.setForeground(new java.awt.Color(42, 74, 56));
        tglAdobe.setText("AdobeXD");
        tglAdobe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglAdobeActionPerformed(evt);
            }
        });
        pnlDiseño.add(tglAdobe);

        tglCss.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tglCss.setForeground(new java.awt.Color(42, 74, 56));
        tglCss.setText("CSS/Tailwind");
        tglCss.setPreferredSize(new java.awt.Dimension(40, 15));
        tglCss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglCssActionPerformed(evt);
            }
        });
        pnlDiseño.add(tglCss);

        tglGoogle.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tglGoogle.setForeground(new java.awt.Color(42, 74, 56));
        tglGoogle.setText("GoogleAnalytics");
        tglGoogle.setPreferredSize(new java.awt.Dimension(40, 15));
        tglGoogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglGoogleActionPerformed(evt);
            }
        });
        pnlDiseño.add(tglGoogle);

        tglMeta.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tglMeta.setForeground(new java.awt.Color(42, 74, 56));
        tglMeta.setText("Meta");
        tglMeta.setPreferredSize(new java.awt.Dimension(40, 15));
        tglMeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglMetaActionPerformed(evt);
            }
        });
        pnlDiseño.add(tglMeta);

        tglAds.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tglAds.setForeground(new java.awt.Color(42, 74, 56));
        tglAds.setText("ADS");
        tglAds.setPreferredSize(new java.awt.Dimension(40, 15));
        tglAds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglAdsActionPerformed(evt);
            }
        });
        pnlDiseño.add(tglAds);

        pnlCompTec.add(pnlDiseño, java.awt.BorderLayout.SOUTH);

        pnlFiltros.add(pnlCompTec);

        pnlIdioma.setBackground(new java.awt.Color(244, 253, 248));
        pnlIdioma.setLayout(new java.awt.BorderLayout());

        lblIdioma.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lblIdioma.setForeground(new java.awt.Color(7, 48, 26));
        lblIdioma.setText("Idioma");
        lblIdioma.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblIdioma.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlIdioma.add(lblIdioma, java.awt.BorderLayout.PAGE_START);

        pnlIdiomas.setBackground(new java.awt.Color(244, 253, 248));
        pnlIdiomas.setLayout(new java.awt.GridLayout(0, 2, 2, 2));

        chkEusk.setBackground(new java.awt.Color(244, 253, 248));
        chkEusk.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkEusk.setForeground(new java.awt.Color(42, 74, 56));
        chkEusk.setText("Euskera");
        chkEusk.setFocusPainted(false);
        chkEusk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEuskActionPerformed(evt);
            }
        });
        pnlIdiomas.add(chkEusk);

        chkCast.setBackground(new java.awt.Color(244, 253, 248));
        chkCast.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkCast.setForeground(new java.awt.Color(42, 74, 56));
        chkCast.setText("Castellano");
        chkCast.setFocusPainted(false);
        chkCast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCastActionPerformed(evt);
            }
        });
        pnlIdiomas.add(chkCast);

        chkIng.setBackground(new java.awt.Color(244, 253, 248));
        chkIng.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkIng.setForeground(new java.awt.Color(42, 74, 56));
        chkIng.setText("Inglés");
        chkIng.setFocusPainted(false);
        chkIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIngActionPerformed(evt);
            }
        });
        pnlIdiomas.add(chkIng);

        chkFra.setBackground(new java.awt.Color(244, 253, 248));
        chkFra.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkFra.setForeground(new java.awt.Color(42, 74, 56));
        chkFra.setText("Francés");
        chkFra.setFocusPainted(false);
        chkFra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFraActionPerformed(evt);
            }
        });
        pnlIdiomas.add(chkFra);

        chkAle.setBackground(new java.awt.Color(244, 253, 248));
        chkAle.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkAle.setForeground(new java.awt.Color(42, 74, 56));
        chkAle.setText("Alemán");
        chkAle.setFocusPainted(false);
        chkAle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAleActionPerformed(evt);
            }
        });
        pnlIdiomas.add(chkAle);

        pnlIdioma.add(pnlIdiomas, java.awt.BorderLayout.CENTER);

        pnlFiltros.add(pnlIdioma);

        pnlTituloTr.setBackground(new java.awt.Color(244, 253, 248));
        pnlTituloTr.setLayout(new java.awt.BorderLayout());

        lblTransversales.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lblTransversales.setForeground(new java.awt.Color(7, 48, 26));
        lblTransversales.setText("Transversales");
        pnlTituloTr.add(lblTransversales, java.awt.BorderLayout.PAGE_START);

        pnlTransversales.setBackground(new java.awt.Color(244, 253, 248));
        pnlTransversales.setLayout(new java.awt.GridLayout(0, 2, 2, 2));

        chkAutnomia.setBackground(new java.awt.Color(244, 253, 248));
        chkAutnomia.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkAutnomia.setForeground(new java.awt.Color(42, 74, 56));
        chkAutnomia.setText("Autonomía");
        pnlTransversales.add(chkAutnomia);

        chkCompromiso.setBackground(new java.awt.Color(244, 253, 248));
        chkCompromiso.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkCompromiso.setForeground(new java.awt.Color(42, 74, 56));
        chkCompromiso.setText("Compromiso");
        pnlTransversales.add(chkCompromiso);

        chkImpl.setBackground(new java.awt.Color(244, 253, 248));
        chkImpl.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkImpl.setForeground(new java.awt.Color(42, 74, 56));
        chkImpl.setText("Implicación");
        chkImpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkImplActionPerformed(evt);
            }
        });
        pnlTransversales.add(chkImpl);

        chkImpl1.setBackground(new java.awt.Color(244, 253, 248));
        chkImpl1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkImpl1.setForeground(new java.awt.Color(42, 74, 56));
        chkImpl1.setText("Implicación");
        chkImpl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkImpl1ActionPerformed(evt);
            }
        });
        pnlTransversales.add(chkImpl1);

        pnlTituloTr.add(pnlTransversales, java.awt.BorderLayout.CENTER);

        pnlFiltros.add(pnlTituloTr);

        pnlContenido.add(pnlFiltros, java.awt.BorderLayout.WEST);

        tablaContenidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Municipio", "Email", "Competencias", "Idiomas", "Transversales"
            }
        ));
        tablaContenidos.setPreferredSize(new java.awt.Dimension(400, 80));
        jScrollPane1.setViewportView(tablaContenidos);

        pnlContenido.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlCentral.add(pnlContenido, java.awt.BorderLayout.SOUTH);

        pnlPrincipal.add(pnlCentral, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 903, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContrActionPerformed
        FrmContraseñaOlvidada frm = new FrmContraseñaOlvidada();
        frm.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frm.setLocationRelativeTo(null);
        frm.setSize(700, 600);
        frm.setVisible(true);
    }//GEN-LAST:event_btnContrActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de que quieres cerrar sesión?",
                "Cerrar Sesión",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
            new FrmLogin().setVisible(true);
            this.dispose();
            // Aquí abres tu pantalla de Login, por ejemplo:
            // new FrmLogin().setVisible(true);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void bntCrearCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCrearCandidatoActionPerformed
        FrmAdminCrearUsuario frm = new FrmAdminCrearUsuario();
        frm.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frm.setLocationRelativeTo(null);
        frm.setSize(700, 600);
        frm.setVisible(true);
    }//GEN-LAST:event_bntCrearCandidatoActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void chkEuskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEuskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEuskActionPerformed

    private void chkCastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCastActionPerformed

    private void chkIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkIngActionPerformed

    private void chkFraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkFraActionPerformed

    private void chkAleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAleActionPerformed

    private void chkImplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkImplActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkImplActionPerformed

    private void tglJavaScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglJavaScriptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglJavaScriptActionPerformed

    private void tglPythonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglPythonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglPythonActionPerformed

    private void tglFigmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglFigmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglFigmaActionPerformed

    private void tglAdobeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglAdobeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglAdobeActionPerformed

    private void tglReactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglReactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglReactActionPerformed

    private void tglNoodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglNoodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglNoodeActionPerformed

    private void tglJavaSqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglJavaSqlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglJavaSqlActionPerformed

    private void tglApacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglApacheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglApacheActionPerformed

    private void tglAwsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglAwsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglAwsActionPerformed

    private void tglKubernetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglKubernetesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglKubernetesActionPerformed

    private void tglLinuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglLinuxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglLinuxActionPerformed

    private void tglDockerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglDockerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglDockerActionPerformed

    private void tglCssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglCssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglCssActionPerformed

    private void tglGoogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglGoogleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglGoogleActionPerformed

    private void tglMetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglMetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglMetaActionPerformed

    private void tglAdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglAdsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglAdsActionPerformed

    private void chkImpl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkImpl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkImpl1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPanelAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCrearCandidato;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnContr;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox chkAle;
    private javax.swing.JCheckBox chkAutnomia;
    private javax.swing.JCheckBox chkCast;
    private javax.swing.JCheckBox chkCompromiso;
    private javax.swing.JCheckBox chkEusk;
    private javax.swing.JCheckBox chkFra;
    private javax.swing.JCheckBox chkImpl;
    private javax.swing.JCheckBox chkImpl1;
    private javax.swing.JCheckBox chkIng;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblCompTec;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTransversales;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlBusqueda;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlCompTec;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlCrearCandidato;
    private javax.swing.JPanel pnlDesarrollo;
    private javax.swing.JPanel pnlDiseño;
    private javax.swing.JPanel pnlFiltros;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlIdioma;
    private javax.swing.JPanel pnlIdiomas;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlTituloTr;
    private javax.swing.JPanel pnlTransversales;
    private javax.swing.JTable tablaContenidos;
    private javax.swing.JToggleButton tglAdobe;
    private javax.swing.JToggleButton tglAds;
    private javax.swing.JToggleButton tglApache;
    private javax.swing.JToggleButton tglAws;
    private javax.swing.JToggleButton tglCss;
    private javax.swing.JToggleButton tglDocker;
    private javax.swing.JToggleButton tglFigma;
    private javax.swing.JToggleButton tglGoogle;
    private javax.swing.JToggleButton tglJavaScript;
    private javax.swing.JToggleButton tglJavaSql;
    private javax.swing.JToggleButton tglKubernetes;
    private javax.swing.JToggleButton tglLinux;
    private javax.swing.JToggleButton tglMeta;
    private javax.swing.JToggleButton tglNoode;
    private javax.swing.JToggleButton tglPython;
    private javax.swing.JToggleButton tglReact;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
