/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package s.z_talent_manager.vista;

/**
 *
 * @author DAW1
 */
public class FrmPanelAdmin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPanelAdmin.class.getName());

    /**
     * Creates new form Prueba2
     */
    public FrmPanelAdmin() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Pantalla completa
        // Hacer el layout responsivo
        pnlPrincipal.setPreferredSize(null);
        
        
        // Placeholder "Search..."
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtSearch.getText().equals("Search...")) {
                    txtSearch.setText("");
                    txtSearch.setForeground(new java.awt.Color(7, 48, 26));
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtSearch.getText().isBlank()) {
                    txtSearch.setText("Search...");
                    txtSearch.setForeground(new java.awt.Color(74, 122, 96));
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnContr = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        pnlCentral = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();
        pnlCrearCandidato = new javax.swing.JPanel();
        bntCrearCandidato = new javax.swing.JButton();
        pnlBusqueda = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        pnlContenido = new javax.swing.JPanel();
        pnlFiltros = new javax.swing.JPanel();
        pnlCompTec = new javax.swing.JPanel();
        lblCompTec = new javax.swing.JLabel();
        lblDatosTecnica = new javax.swing.JPanel();
        chkSql = new javax.swing.JCheckBox();
        chkJava = new javax.swing.JCheckBox();
        chkPython = new javax.swing.JCheckBox();
        chkReact = new javax.swing.JCheckBox();
        chkDocker = new javax.swing.JCheckBox();
        chkAws = new javax.swing.JCheckBox();
        chkNoode = new javax.swing.JCheckBox();
        jToggleButton1 = new javax.swing.JToggleButton();
        pnlIdioma = new javax.swing.JPanel();
        lblIdioma = new javax.swing.JLabel();
        pnlIdiomas = new javax.swing.JPanel();
        chkEusk = new javax.swing.JCheckBox();
        chkCast = new javax.swing.JCheckBox();
        chkIng = new javax.swing.JCheckBox();
        chkFra = new javax.swing.JCheckBox();
        chkAle = new javax.swing.JCheckBox();
        chkPort = new javax.swing.JCheckBox();
        pnlTituloTr = new javax.swing.JPanel();
        lblTransversales = new javax.swing.JLabel();
        pnlTransversales = new javax.swing.JPanel();
        chkAutnomia = new javax.swing.JCheckBox();
        chkCompromiso = new javax.swing.JCheckBox();
        chkImpl = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaContenidos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(211, 254, 234));
        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(211, 254, 234));
        pnlHeader.setPreferredSize(new java.awt.Dimension(1100, 90));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        pnlLogo.setBackground(new java.awt.Color(211, 254, 234));

        lblLogo.setBackground(new java.awt.Color(211, 254, 234));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        lblLogo.setPreferredSize(new java.awt.Dimension(400, 85));
        pnlLogo.add(lblLogo);

        pnlHeader.add(pnlLogo, java.awt.BorderLayout.WEST);

        pnlBotones.setBackground(new java.awt.Color(211, 254, 234));
        pnlBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnContr.setBackground(new java.awt.Color(211, 254, 234));
        btnContr.setForeground(new java.awt.Color(7, 48, 26));
        btnContr.setText("CAMBIAR CONTRASEÑA");
        btnContr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContr.setFocusPainted(false);
        btnContr.setPreferredSize(new java.awt.Dimension(180, 35));
        btnContr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContrActionPerformed(evt);
            }
        });
        pnlBotones.add(btnContr);

        btnSalir.setBackground(new java.awt.Color(211, 254, 234));
        btnSalir.setForeground(new java.awt.Color(7, 48, 26));
        btnSalir.setText("↪");
        btnSalir.setFocusPainted(false);
        btnSalir.setPreferredSize(new java.awt.Dimension(40, 35));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlBotones.add(btnSalir);

        pnlHeader.add(pnlBotones, java.awt.BorderLayout.EAST);

        pnlPrincipal.add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlCentral.setBackground(new java.awt.Color(211, 254, 234));
        pnlCentral.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 30, 10, 30));
        pnlCentral.setLayout(new java.awt.BorderLayout());

        lblBienvenida.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(7, 48, 26));
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("!Bienvenida/o, Admin!");
        lblBienvenida.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblBienvenida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlCentral.add(lblBienvenida, java.awt.BorderLayout.NORTH);

        pnlCrearCandidato.setBackground(new java.awt.Color(211, 254, 234));
        pnlCrearCandidato.setPreferredSize(new java.awt.Dimension(0, 45));

        bntCrearCandidato.setBackground(new java.awt.Color(51, 153, 102));
        bntCrearCandidato.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        bntCrearCandidato.setForeground(new java.awt.Color(255, 255, 255));
        bntCrearCandidato.setText("Crear Candidato");
        bntCrearCandidato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntCrearCandidato.setFocusPainted(false);
        bntCrearCandidato.setPreferredSize(new java.awt.Dimension(140, 34));
        bntCrearCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCrearCandidatoActionPerformed(evt);
            }
        });
        pnlCrearCandidato.add(bntCrearCandidato);

        pnlBusqueda.setBackground(new java.awt.Color(211, 254, 234));
        pnlBusqueda.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));

        txtSearch.setBackground(new java.awt.Color(248, 253, 249));
        txtSearch.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(74, 122, 96));
        txtSearch.setText("Search...");
        txtSearch.setFocusTraversalPolicyProvider(true);
        txtSearch.setPreferredSize(new java.awt.Dimension(700, 36));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        pnlBusqueda.add(txtSearch);

        btnBuscar.setBackground(new java.awt.Color(51, 153, 102));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("🔍");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setFocusPainted(false);
        btnBuscar.setPreferredSize(new java.awt.Dimension(42, 36));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        pnlBusqueda.add(btnBuscar);

        pnlCrearCandidato.add(pnlBusqueda);

        pnlCentral.add(pnlCrearCandidato, java.awt.BorderLayout.CENTER);

        pnlContenido.setBackground(new java.awt.Color(211, 254, 234));
        pnlContenido.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 10, 20));
        pnlContenido.setPreferredSize(new java.awt.Dimension(0, 450));
        pnlContenido.setLayout(new java.awt.BorderLayout());

        pnlFiltros.setBackground(new java.awt.Color(244, 253, 248));
        pnlFiltros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 240, 212)));
        pnlFiltros.setPreferredSize(new java.awt.Dimension(220, 0));
        pnlFiltros.setLayout(new javax.swing.BoxLayout(pnlFiltros, javax.swing.BoxLayout.Y_AXIS));

        pnlCompTec.setBackground(new java.awt.Color(244, 253, 248));
        pnlCompTec.setLayout(new java.awt.BorderLayout());

        lblCompTec.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lblCompTec.setForeground(new java.awt.Color(7, 48, 26));
        lblCompTec.setText("Competencia Técnica");
        pnlCompTec.add(lblCompTec, java.awt.BorderLayout.NORTH);

        lblDatosTecnica.setBackground(new java.awt.Color(244, 253, 248));
        lblDatosTecnica.setLayout(new java.awt.GridLayout(0, 2, 4, 2));

        chkSql.setBackground(new java.awt.Color(244, 253, 248));
        chkSql.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkSql.setForeground(new java.awt.Color(42, 74, 56));
        chkSql.setText("SQL");
        chkSql.setFocusPainted(false);
        chkSql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSqlActionPerformed(evt);
            }
        });
        lblDatosTecnica.add(chkSql);

        chkJava.setBackground(new java.awt.Color(244, 253, 248));
        chkJava.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkJava.setForeground(new java.awt.Color(42, 74, 56));
        chkJava.setText("Java");
        chkJava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkJavaActionPerformed(evt);
            }
        });
        lblDatosTecnica.add(chkJava);

        chkPython.setBackground(new java.awt.Color(244, 253, 248));
        chkPython.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkPython.setForeground(new java.awt.Color(42, 74, 56));
        chkPython.setText("Python");
        chkPython.setFocusPainted(false);
        lblDatosTecnica.add(chkPython);

        chkReact.setBackground(new java.awt.Color(244, 253, 248));
        chkReact.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkReact.setForeground(new java.awt.Color(42, 74, 56));
        chkReact.setText("React");
        chkReact.setFocusPainted(false);
        lblDatosTecnica.add(chkReact);

        chkDocker.setBackground(new java.awt.Color(244, 253, 248));
        chkDocker.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkDocker.setForeground(new java.awt.Color(42, 74, 56));
        chkDocker.setText("Docker");
        chkDocker.setFocusPainted(false);
        chkDocker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDockerActionPerformed(evt);
            }
        });
        lblDatosTecnica.add(chkDocker);

        chkAws.setBackground(new java.awt.Color(244, 253, 248));
        chkAws.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkAws.setForeground(new java.awt.Color(42, 74, 56));
        chkAws.setText("AWS");
        chkAws.setFocusable(false);
        lblDatosTecnica.add(chkAws);

        chkNoode.setBackground(new java.awt.Color(244, 253, 248));
        chkNoode.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkNoode.setForeground(new java.awt.Color(42, 74, 56));
        chkNoode.setText("Noode.js");
        chkNoode.setFocusPainted(false);
        lblDatosTecnica.add(chkNoode);

        jToggleButton1.setText("Prueba");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        lblDatosTecnica.add(jToggleButton1);

        pnlCompTec.add(lblDatosTecnica, java.awt.BorderLayout.CENTER);

        pnlFiltros.add(pnlCompTec);

        pnlIdioma.setBackground(new java.awt.Color(244, 253, 248));
        pnlIdioma.setLayout(new java.awt.BorderLayout());

        lblIdioma.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lblIdioma.setForeground(new java.awt.Color(7, 48, 26));
        lblIdioma.setText("Idioma");
        lblIdioma.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblIdioma.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlIdioma.add(lblIdioma, java.awt.BorderLayout.PAGE_START);

        pnlIdiomas.setBackground(new java.awt.Color(244, 253, 248));
        pnlIdiomas.setLayout(new java.awt.GridLayout(0, 2, 3, 2));

        chkEusk.setBackground(new java.awt.Color(244, 253, 248));
        chkEusk.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkEusk.setForeground(new java.awt.Color(42, 74, 56));
        chkEusk.setText("Euskera");
        chkEusk.setFocusPainted(false);
        chkEusk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEuskActionPerformed(evt);
            }
        });
        pnlIdiomas.add(chkEusk);

        chkCast.setBackground(new java.awt.Color(244, 253, 248));
        chkCast.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkCast.setForeground(new java.awt.Color(42, 74, 56));
        chkCast.setText("Castellano");
        chkCast.setFocusPainted(false);
        chkCast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCastActionPerformed(evt);
            }
        });
        pnlIdiomas.add(chkCast);

        chkIng.setBackground(new java.awt.Color(244, 253, 248));
        chkIng.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkIng.setForeground(new java.awt.Color(42, 74, 56));
        chkIng.setText("Inglés");
        chkIng.setFocusPainted(false);
        chkIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIngActionPerformed(evt);
            }
        });
        pnlIdiomas.add(chkIng);

        chkFra.setBackground(new java.awt.Color(244, 253, 248));
        chkFra.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkFra.setForeground(new java.awt.Color(42, 74, 56));
        chkFra.setText("Francés");
        chkFra.setFocusPainted(false);
        chkFra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFraActionPerformed(evt);
            }
        });
        pnlIdiomas.add(chkFra);

        chkAle.setBackground(new java.awt.Color(244, 253, 248));
        chkAle.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkAle.setForeground(new java.awt.Color(42, 74, 56));
        chkAle.setText("Alemán");
        chkAle.setFocusPainted(false);
        chkAle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAleActionPerformed(evt);
            }
        });
        pnlIdiomas.add(chkAle);

        chkPort.setBackground(new java.awt.Color(244, 253, 248));
        chkPort.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkPort.setForeground(new java.awt.Color(42, 74, 56));
        chkPort.setText("Portugués");
        chkPort.setFocusPainted(false);
        chkPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPortActionPerformed(evt);
            }
        });
        pnlIdiomas.add(chkPort);

        pnlIdioma.add(pnlIdiomas, java.awt.BorderLayout.CENTER);

        pnlFiltros.add(pnlIdioma);

        pnlTituloTr.setBackground(new java.awt.Color(244, 253, 248));
        pnlTituloTr.setLayout(new java.awt.BorderLayout());

        lblTransversales.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lblTransversales.setForeground(new java.awt.Color(7, 48, 26));
        lblTransversales.setText("Transversales");
        pnlTituloTr.add(lblTransversales, java.awt.BorderLayout.PAGE_START);

        pnlTransversales.setLayout(new java.awt.GridLayout(0, 1, 3, 0));

        chkAutnomia.setBackground(new java.awt.Color(244, 253, 248));
        chkAutnomia.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkAutnomia.setForeground(new java.awt.Color(42, 74, 56));
        chkAutnomia.setText("Autonomía");
        pnlTransversales.add(chkAutnomia);

        chkCompromiso.setBackground(new java.awt.Color(244, 253, 248));
        chkCompromiso.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkCompromiso.setForeground(new java.awt.Color(42, 74, 56));
        chkCompromiso.setText("Compromiso");
        pnlTransversales.add(chkCompromiso);

        chkImpl.setBackground(new java.awt.Color(244, 253, 248));
        chkImpl.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkImpl.setForeground(new java.awt.Color(42, 74, 56));
        chkImpl.setText("Implicación");
        chkImpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkImplActionPerformed(evt);
            }
        });
        pnlTransversales.add(chkImpl);

        pnlTituloTr.add(pnlTransversales, java.awt.BorderLayout.CENTER);

        pnlFiltros.add(pnlTituloTr);

        pnlContenido.add(pnlFiltros, java.awt.BorderLayout.WEST);

        tablaContenidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Municipio", "Email", "Competencias", "Idiomas", "Transversales"
            }
        ));
        tablaContenidos.setPreferredSize(new java.awt.Dimension(400, 80));
        jScrollPane1.setViewportView(tablaContenidos);

        pnlContenido.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlCentral.add(pnlContenido, java.awt.BorderLayout.SOUTH);

        pnlPrincipal.add(pnlCentral, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 903, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContrActionPerformed
        contraseñaOlvidada();
    }//GEN-LAST:event_btnContrActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void bntCrearCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCrearCandidatoActionPerformed
        navegarACrearUsuario();
    }//GEN-LAST:event_bntCrearCandidatoActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void chkSqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSqlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSqlActionPerformed

    private void chkJavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkJavaActionPerformed

    private void chkDockerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDockerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDockerActionPerformed

    private void chkEuskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEuskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEuskActionPerformed

    private void chkCastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCastActionPerformed

    private void chkIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkIngActionPerformed

    private void chkFraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkFraActionPerformed

    private void chkAleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAleActionPerformed

    private void chkPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPortActionPerformed

    private void chkImplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkImplActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkImplActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPanelAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCrearCandidato;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnContr;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox chkAle;
    private javax.swing.JCheckBox chkAutnomia;
    private javax.swing.JCheckBox chkAws;
    private javax.swing.JCheckBox chkCast;
    private javax.swing.JCheckBox chkCompromiso;
    private javax.swing.JCheckBox chkDocker;
    private javax.swing.JCheckBox chkEusk;
    private javax.swing.JCheckBox chkFra;
    private javax.swing.JCheckBox chkImpl;
    private javax.swing.JCheckBox chkIng;
    private javax.swing.JCheckBox chkJava;
    private javax.swing.JCheckBox chkNoode;
    private javax.swing.JCheckBox chkPort;
    private javax.swing.JCheckBox chkPython;
    private javax.swing.JCheckBox chkReact;
    private javax.swing.JCheckBox chkSql;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblCompTec;
    private javax.swing.JPanel lblDatosTecnica;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTransversales;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlBusqueda;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlCompTec;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlCrearCandidato;
    private javax.swing.JPanel pnlFiltros;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlIdioma;
    private javax.swing.JPanel pnlIdiomas;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlTituloTr;
    private javax.swing.JPanel pnlTransversales;
    private javax.swing.JTable tablaContenidos;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void navegarACrearUsuario() {
        FrmAdminCrearUsuario frm = new FrmAdminCrearUsuario();
        frm.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        frm.setVisible(true);
        this.dispose(); // Cierra la ventana actual
    }
    
    private void contraseñaOlvidada(){
        FrmContraseñaOlvidada frm = new FrmContraseñaOlvidada();
        frm.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        frm.setVisible(true);
        this.dispose(); // Cierra la ventana actual
    }
}
