/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package s.z_talent_manager.vista;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import s.z_talent_manager.modelo.Candidato;
import s.z_talent_manager.modelo.Sesion;
import s.z_talent_manager.servicio.ZTalentManagerServicio;

/**
 *
 * @author fabia
 */
public class FrmVentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmVentanaPrincipal.class.getName());

    private ZTalentManagerServicio servicio = ZTalentManagerServicio.getServicio();

    /**
     * Creates new form FrmVentanaPrincipal
     */
    public FrmVentanaPrincipal() {
        initComponents();
        setTitle("Z-TALENT MANAGER"); //colocar titulo en la ventana
        setLocationRelativeTo(null); // centra la ventana

        FrmInfoPersonal panelInfo = new FrmInfoPersonal();
        FrmExperiencias panelExp = new FrmExperiencias();
        FrmTitulacion panelTit = new FrmTitulacion();
        FrmCompetencias panelComp = new FrmCompetencias();

        tabbedPane.addTab("Información personal", panelInfo);
        tabbedPane.addTab("Experiencias", panelExp);
        tabbedPane.addTab("Titulación", panelTit);
        tabbedPane.addTab("Competencias", panelComp);

        cargarDatosDesdeServicio(panelInfo, panelExp, panelTit, panelComp);
    }

    private void cargarDatosDesdeServicio(
            FrmInfoPersonal panelInfo,
            FrmExperiencias panelExp,
            FrmTitulacion panelTit,
            FrmCompetencias panelComp) {
        try {
            Candidato candidato = Sesion.getCandidato();
            if (candidato == null) {
                JOptionPane.showMessageDialog(this,
                        "No se encontró el candidato.",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            jLabel4.setText("¡Bienvenido/a, " + candidato.getNombre() + "!");
            panelInfo.cargarDatos(candidato);

            panelExp.cargarDatos(candidato.getExperiencias());
            panelTit.cargarDatos(candidato.getCandidatoTitulaciones());
            panelComp.cargarDatos(
                    candidato.getCandidatoIdiomas(),
                    candidato.getCandidatoTecnicas(),
                    candidato.getCandidatoTransversales()
            );

        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error cargando datos", ex);
            JOptionPane.showMessageDialog(this,
                    "Error al cargar los datos.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalirMain = new javax.swing.JButton();
        btnCambiarContraseñaMain = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(7, 48, 26));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 102)));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 68));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(211, 254, 234));
        jLabel1.setText("Z-TALENT MANAGER");

        btnSalirMain.setBackground(new java.awt.Color(51, 153, 102));
        btnSalirMain.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalirMain.setForeground(new java.awt.Color(211, 254, 234));
        btnSalirMain.setText("Salir");
        btnSalirMain.setBorderPainted(false);
        btnSalirMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMainActionPerformed(evt);
            }
        });

        btnCambiarContraseñaMain.setBackground(new java.awt.Color(7, 48, 26));
        btnCambiarContraseñaMain.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCambiarContraseñaMain.setForeground(new java.awt.Color(211, 254, 234));
        btnCambiarContraseñaMain.setText("Cambiar contraseña");
        btnCambiarContraseñaMain.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 102), 1, true));
        btnCambiarContraseñaMain.setContentAreaFilled(false);
        btnCambiarContraseñaMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarContraseñaMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(btnCambiarContraseñaMain)
                .addGap(18, 18, 18)
                .addComponent(btnSalirMain)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSalirMain)
                    .addComponent(btnCambiarContraseñaMain, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(211, 254, 234));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 204, 153)));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 68));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(7, 48, 26));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("¡Bienvenido/a, Usuario!");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mantén tu CV actualizado");

        tabbedPane.setBackground(new java.awt.Color(211, 254, 234));
        tabbedPane.setForeground(new java.awt.Color(7, 48, 26));
        jScrollPane1.setViewportView(tabbedPane);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(305, 305, 305))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarContraseñaMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarContraseñaMainActionPerformed
        this.setVisible(false);

        FrmContraseñaOlvidada frmContraseña = new FrmContraseñaOlvidada();
        frmContraseña.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frmContraseña.setLocationRelativeTo(null);
        frmContraseña.setVisible(true);

        frmContraseña.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                setVisible(true);
            }
        });

    }//GEN-LAST:event_btnCambiarContraseñaMainActionPerformed

    private void btnSalirMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMainActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            FlatLightLaf.setup();

            UIManager.put("TabbedPane.selectedBackground", new Color(51, 153, 102));
            UIManager.put("TabbedPane.background", new Color(211, 254, 234));
            UIManager.put("TabbedPane.foreground", new Color(7, 48, 26));
            UIManager.put("TabbedPane.selectedForeground", new Color(211, 254, 234));
            UIManager.put("TabbedPane.underlineColor", new Color(51, 153, 102));
            UIManager.put("TabbedPane.hoverColor", new Color(102, 204, 153));

        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmVentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarContraseñaMain;
    private javax.swing.JButton btnSalirMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

}
